---
include:
  - board: sofle_left
    shield: nice_view
  - board: sofle_right
    shield: nice_view_gem
  - board: sofle_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: _sofle_studio_left
  - board: sofle_left
    shield: settings_reset
